import type { PicksFile, ResultsFile, ValuesFile } from "./schema";

// Canonical example payloads — one per market shape a model might emit. These are
// written to dashboard_feed/_examples/ as reference for each folder's agent, and
// re-used as fixtures. Values are illustrative, not a real slate.

export const examplePicks: PicksFile[] = [
  // --- College basketball: spread / total / moneyline / first half -----------
  {
    contract_version: "1.0",
    source: "bet-screen",
    sport: "cbb",
    slate_date: "2026-01-15",
    generated_at: "2026-01-15T14:30:00Z",
    model_version: "cbb-v2-mc",
    mode: "LIVE",
    event_context: "Thursday CBB slate",
    bets: [
      {
        bet_id: "bet-screen-2026-01-15-duke-unc-spread",
        event: "Duke @ North Carolina",
        event_start: "2026-01-16T00:00:00Z",
        market: "spread",
        selection: "Duke",
        side: "away",
        line: -3.5,
        odds_american: -110,
        book: "DraftKings",
        model_prob: 0.58,
        market_prob: 0.524,
        edge: 0.056,
        ev_pct: 0.068,
        stake_units: 1.5,
        confidence: "high",
        tags: ["rivalry"],
        details: { pred_margin: 5.9, market_spread: 3.5 },
      },
      {
        bet_id: "bet-screen-2026-01-15-duke-unc-total",
        event: "Duke @ North Carolina",
        event_start: "2026-01-16T00:00:00Z",
        market: "total",
        selection: "Under 148.5",
        side: "under",
        line: 148.5,
        odds_american: -108,
        book: "FanDuel",
        model_prob: 0.55,
        market_prob: 0.519,
        edge: 0.031,
        ev_pct: 0.032,
        stake_units: 0.75,
        confidence: "medium",
        details: { pred_total: 143.2 },
      },
      {
        bet_id: "bet-screen-2026-01-15-kansas-1h",
        event: "Kansas @ Baylor",
        event_start: "2026-01-16T01:00:00Z",
        market: "first_half_spread",
        selection: "Kansas 1H",
        side: "away",
        line: 1.5,
        odds_american: -105,
        book: "DraftKings",
        model_prob: 0.545,
        stake_units: 0.5,
        confidence: "low",
        tags: ["1H"],
      },
    ],
  },

  // --- PGA: outrights + matchup, PAPER mode (still on the go/no-go gate) ------
  {
    contract_version: "1.0",
    source: "golf-modeling",
    sport: "pga",
    slate_date: "2026-07-22",
    generated_at: "2026-07-22T13:05:00Z",
    model_version: "targets-2026.07",
    mode: "PAPER",
    event_context: "Rocket Mortgage Classic",
    notes: "Paper only until mean CLV proves positive across more events.",
    bets: [
      {
        bet_id: "golf-2026-07-22-scheffler-win",
        event: "Rocket Mortgage Classic",
        event_start: "2026-07-23T12:00:00Z",
        market: "outright_win",
        selection: "Scottie Scheffler",
        line: null,
        odds_american: 650,
        book: "DraftKings",
        model_prob: 0.18,
        market_prob: 0.133,
        edge: 0.047,
        ev_pct: 0.31,
        stake_units: 0.5,
        confidence: "medium",
        tags: ["outright"],
        details: { sg_last_24: 1.9, sg_putt: 0.4 },
      },
      {
        bet_id: "golf-2026-07-22-cantlay-top10",
        event: "Rocket Mortgage Classic",
        event_start: "2026-07-23T12:00:00Z",
        market: "outright_top10",
        selection: "Patrick Cantlay",
        odds_american: 210,
        book: "FanDuel",
        model_prob: 0.42,
        market_prob: 0.323,
        edge: 0.097,
        ev_pct: 0.30,
        stake_units: 1.0,
        confidence: "high",
        tags: ["outright", "top10"],
      },
      {
        bet_id: "golf-2026-07-22-fitz-vs-morikawa-72h",
        event: "Rocket Mortgage Classic",
        event_start: "2026-07-23T12:00:00Z",
        market: "matchup",
        market_label: "72-Hole Matchup",
        selection: "Matt Fitzpatrick",
        odds_american: -115,
        book: "FanDuel",
        model_prob: 0.55,
        market_prob: 0.535,
        edge: 0.015,
        ev_pct: 0.05,
        stake_units: 0.5,
        confidence: "medium",
        tags: ["matchup", "72_hole"],
        details: { opponent: "Collin Morikawa", matchup_type: "72_hole", sg_last_24: 1.1 },
      },
    ],
  },

  // --- College football: totals + spread -------------------------------------
  {
    contract_version: "1.0",
    source: "cfb-modeling",
    sport: "cfb",
    slate_date: "2026-09-05",
    generated_at: "2026-09-05T12:00:00Z",
    model_version: "ppp-xgb-2026",
    mode: "PAPER",
    event_context: "Week 2",
    notes: "UNDER-only asymmetry + early-season 4th-down aggressiveness ATS, forward-validating.",
    bets: [
      {
        bet_id: "cfb-modeling-2026-w2-osu-tex-under",
        event: "Ohio State @ Texas",
        event_start: "2026-09-05T23:30:00Z",
        market: "total",
        selection: "Under 52.5",
        side: "under",
        line: 52.5,
        odds_american: -110,
        book: "DraftKings",
        model_prob: 0.57,
        market_prob: 0.524,
        edge: 0.046,
        ev_pct: 0.058,
        stake_units: 1.0,
        confidence: "medium",
        details: { proj_total: 47.1, strategy: "UNDER4" },
      },
      {
        bet_id: "cfb-modeling-2026-w2-app-ga-ats",
        event: "Appalachian State @ Georgia",
        market: "spread",
        selection: "Appalachian State",
        side: "away",
        line: 24.5,
        odds_american: -105,
        book: "FanDuel",
        model_prob: 0.54,
        stake_units: 0.5,
        confidence: "low",
        tags: ["early_ats", "dog"],
        details: { go_rate_pick: 0.71, tier: "A" },
      },
    ],
  },

  // --- DFS: a lineup as a single "bet" (lineup lives in details) -------------
  {
    contract_version: "1.0",
    source: "dfs-engine",
    sport: "wnba",
    slate_date: "2026-07-22",
    generated_at: "2026-07-22T18:40:00Z",
    model_version: "spine-2026.07",
    mode: "LIVE",
    event_context: "WNBA main slate (5 games)",
    bets: [
      {
        bet_id: "dfs-engine-2026-07-22-wnba-gpp-1",
        event: "WNBA GPP — $5 Jam",
        event_start: "2026-07-22T23:00:00Z",
        market: "dfs_lineup",
        market_label: "DK GPP lineup",
        selection: "GPP Lineup #1",
        odds_american: 0,
        book: "DraftKings",
        model_prob: null,
        stake_units: 1.0,
        confidence: "medium",
        tags: ["gpp", "wnba"],
        details: {
          contest: "$5 Jam (GPP)",
          entry_fee: 5,
          salary: 49800,
          proj: 261.4,
          ceil: 318.0,
          avg_own: 22.1,
          players: [
            { name: "A'ja Wilson", pos: "F", salary: 11200, proj: 51.2, own: 34 },
            { name: "Caitlin Clark", pos: "G", salary: 10600, proj: 47.9, own: 41 },
            { name: "Sabrina Ionescu", pos: "G", salary: 8900, proj: 39.1, own: 18 },
            { name: "Nneka Ogwumike", pos: "F", salary: 7400, proj: 31.0, own: 12 },
            { name: "Kelsey Plum", pos: "G", salary: 7100, proj: 30.4, own: 15 },
            { name: "Rhyne Howard", pos: "F", salary: 6300, proj: 28.8, own: 9 },
          ],
        },
      },
    ],
  },

  // --- NFL: spreads / totals + player props ----------------------------------
  {
    contract_version: "1.0",
    source: "nfl-modeling",
    sport: "nfl",
    slate_date: "2026-09-13",
    generated_at: "2026-09-11T15:00:00Z",
    model_version: "nfl-v1",
    mode: "PAPER",
    event_context: "Week 2",
    bets: [
      {
        bet_id: "nfl-modeling-2026-wk2-cin-kc-ats",
        event: "Bengals @ Chiefs",
        event_start: "2026-09-13T20:25:00Z",
        market: "spread",
        selection: "Kansas City Chiefs",
        side: "home",
        line: -3.5,
        odds_american: -110,
        book: "DraftKings",
        model_prob: 0.57,
        market_prob: 0.524,
        edge: 0.046,
        ev_pct: 0.06,
        stake_units: 1.0,
        confidence: "medium",
        tags: ["spread"],
      },
      {
        bet_id: "nfl-modeling-2026-wk2-cin-kc-total",
        event: "Bengals @ Chiefs",
        market: "total",
        selection: "Under 47.5",
        side: "under",
        line: 47.5,
        odds_american: -108,
        book: "FanDuel",
        model_prob: 0.55,
        stake_units: 0.75,
        confidence: "low",
        tags: ["total"],
      },
      {
        bet_id: "nfl-modeling-2026-wk2-mahomes-passyds-o",
        event: "Bengals @ Chiefs",
        market: "prop",
        market_label: "Passing Yards",
        selection: "Patrick Mahomes Over 275.5",
        side: "over",
        line: 275.5,
        odds_american: -115,
        book: "DraftKings",
        model_prob: 0.58,
        edge: 0.045,
        ev_pct: 0.05,
        stake_units: 1.0,
        confidence: "medium",
        tags: ["prop", "pass_yds"],
        details: { player: "Patrick Mahomes", stat: "pass_yds", team: "KC" },
      },
      {
        bet_id: "nfl-modeling-2026-wk2-barkley-rushyds-u",
        event: "Eagles @ Cowboys",
        market: "prop",
        market_label: "Rushing Yards",
        selection: "Saquon Barkley Under 89.5",
        side: "under",
        line: 89.5,
        odds_american: -110,
        book: "FanDuel",
        model_prob: 0.56,
        ev_pct: 0.07,
        stake_units: 0.75,
        confidence: "medium",
        tags: ["prop", "rush_yds"],
        details: { player: "Saquon Barkley", stat: "rush_yds", team: "PHI" },
      },
    ],
  },
];

// Grading update for the golf slate above — shows the results-file shape.
export const exampleResults: ResultsFile[] = [
  {
    contract_version: "1.0",
    source: "golf-modeling",
    sport: "pga",
    slate_date: "2026-07-22",
    graded_at: "2026-07-27T23:30:00Z",
    results: [
      {
        bet_id: "golf-2026-07-22-scheffler-win",
        result: "loss",
        closing_odds_american: 500,
        clv_pct: -0.09,
        pnl_units: -0.5,
        actual: { finish: 4 },
      },
      {
        bet_id: "golf-2026-07-22-cantlay-top10",
        result: "win",
        closing_odds_american: 175,
        clv_pct: 0.11,
        pnl_units: 2.1,
        actual: { finish: 6 },
      },
      {
        bet_id: "golf-2026-07-22-fitz-vs-morikawa-72h",
        result: "win",
        closing_odds_american: -105,
        clv_pct: 0.04,
        pnl_units: 0.43,
        actual: { fitzpatrick_finish: 8, morikawa_finish: 15 },
      },
    ],
  },
];

// DFS value plays (display-only). One file per (sport, slate day). WNBA/NFL carry
// team+position; golf & tennis leave them blank. NFL here is the empty-slate shape.
export const exampleValues: ValuesFile[] = [
  {
    contract_version: "1.0",
    source: "dfs-engine",
    sport: "wnba",
    site: "draftkings",
    slate_date: "2026-08-10",
    slate_label: "Main",
    generated_at: "2026-08-10T20:00:00Z",
    values: [
      { rank: 1, name: "A'ja Wilson", team: "LVA", position: "F", salary: 11200, proj: 51.2, value: 4.57, ceiling: 63.0, ownership: 0.34, exposure: 0.4 },
      { rank: 2, name: "Nneka Ogwumike", team: "SEA", position: "F", salary: 7400, proj: 33.0, value: 4.46, ceiling: 40.0, ownership: 0.12, exposure: 0.4 },
      { rank: 3, name: "Sabrina Ionescu", team: "NY", position: "G", salary: 8900, proj: 39.1, value: 4.39, ceiling: 47.0, ownership: 0.18, exposure: 0.35 },
      { rank: 4, name: "Kelsey Plum", team: "LVA", position: "G", salary: 7100, proj: 30.4, value: 4.28, ceiling: 38.0, ownership: 0.15, exposure: 0.3 },
      { rank: 5, name: "Rae Burrell", team: "LVA", position: "G", salary: 8300, proj: 24.3, value: 2.93, ceiling: 31.0, ownership: 0.14, exposure: 0.25 },
    ],
  },
  {
    contract_version: "1.0",
    source: "dfs-engine",
    sport: "golf",
    site: "draftkings",
    slate_date: "2026-08-06",
    slate_label: "Main",
    generated_at: "2026-08-06T12:00:00Z",
    values: [
      { rank: 1, name: "Maverick McNealy", team: "", position: "", salary: 7600, proj: 63.2, value: 8.32, ceiling: 100.0 },
      { rank: 2, name: "Scottie Scheffler", team: "", position: "", salary: 11200, proj: 92.5, value: 8.26, ceiling: 130.0 },
      { rank: 3, name: "Ludvig Aberg", team: "", position: "", salary: 9800, proj: 80.1, value: 8.17, ceiling: 118.0 },
    ],
  },
  {
    contract_version: "1.0",
    source: "dfs-engine",
    sport: "nfl",
    site: "draftkings",
    slate_date: "2026-08-10",
    slate_label: "Main",
    generated_at: "2026-08-10T20:00:00Z",
    values: [],
  },
];
